swagger:
  outputDirectory: ./dist
  entryFile: 
    - ./src/controllers/*
  outputFormat: OpenApi_3
  name: Elasticsearch service
  description: This service is the interface to Elasticsearch and Kibana.
  license: MIT
  produces: [application/json]
  version: 0.0.1
  securityDefinitions:
    default:
      type: apiKey
      in: header
      name: Authorization
    secondAuthenticator:
      type: apiKey
      in: header
      name: Authorization
